---
title: "Unsupervised Learning Assignment 1"
author: "Temweka Chirwa (CHRTEM001)"
date: "16/08/2019"
output: html_document
---

Importing data
```{r}
TrackRecords <- read.csv("C:/Users/TemwekaC/OneDrive/Documents/Semester2/Unsupervised Learning/Assignment 1/TrackRecords.csv")
UN_Statistics <- read.csv("C:/Users/TemwekaC/OneDrive/Documents/Semester2/Unsupervised Learning/Assignment 1/UN_Statistics.csv")

dir.create("data")
save(TrackRecords,UN_Statistics, file = "data/InitialData.RData")
```

```{r}
load("data/InitialData.RData")
```

## Exploration of the UN Dataset
```{r}
head(UN_Statistics)
dim(UN_Statistics)

row.names(UN_Statistics) <- UN_Statistics[,1]
UN_Statistics <- UN_Statistics[,-1]

```

```{r}
par(mfrow = c(2, 2))
for (i in 1:5){
  plot(sort(UN_Statistics[,i]), ylab = colnames(UN_Statistics)[i])
}

for (i in 1:5){
  hist((UN_Statistics[,i]), xlab = colnames(UN_Statistics)[i], breaks = 20, main = paste0("Histogram of ", colnames(UN_Statistics)[i]))
}

pairs(UN_Statistics)

#Also check for correlation
boxplot(UN_Statistics)
```

```{r}
library(cluster)
library(MASS)
library(smacof)
```

```{r}
data("eurodist")
eurodistmatrix = as.matrix(eurodist)
eurodist2 = eurodistmatrix[c(1,3,7,8,12,14,17:21), c(1,3,7,8,12,14,17:21)]
eurodist2matrix = as.dist(eurodist2)
```

```{r}
UN_Stat_dist <- dist(scale(UN_Statistics))
UN_Stat_dist
```
```{r}
UN_dist_daisy <- daisy(scale(UN_Statistics), metric = "euclidean")
UN_dist_daisy
```

```{r}
UN.complete.euc <- hclust(UN_Stat_dist,method="complete")
plot(UN.complete.euc)
UN_clusvec <- cutree(UN.complete.euc, k=5)
```

```{r}
UN_Eucledian <- cmdscale(UN_Stat_dist)
# create empty plot
plot (UN_Eucledian)
UN_Eucledian 
#ensure you list enough colours for the number of clusters
colvec <- c("green","gold","blue","red","black", "violet")
for (i in 1:length(UN_Eucledian[,1]))
  text (UN_Eucledian[i,1],UN_Eucledian[i,2],rownames(UN_Statistics)[i],col=colvec[UN_clusvec[i]],cex=0.85)
```

```{r}
UN_Eucledian1 <- cmdscale(UN_Stat_dist, k =1)
# create empty plot

plot(1, type="n",xlim=c(-3,4.2), ylim = c(0.5,1.5), xlab = "Euclidean Distance")
#ensure you list enough colours for the number of clusters
colvec <- c("green","gold","blue","red","black", "violet")
for (i in 1:length(UN_Eucledian1[,1]))
  points(x=UN_Eucledian1[i,1],y=1, col=colvec[UN_clusvec[i]],cex=0.85)

```

```{r}
UN_Eucledian
UN_Eucledian1
```



## Task 2
## About the Dataset
```{r}
head(TrackRecords)
```


## Exploration of the Track Dataset
```{r}

dim(TrackRecords)
row.names(TrackRecords) <- TrackRecords[,2] #Use the country names as labels for each row
colnames(TrackRecords)
TrackRecords <- TrackRecords[,-c(1,2)] #Removing the ID columns, ie, obs and country name
```

```{r}
par(mfrow = c(2, 2))
for (i in 1:7){
  plot(sort(TrackRecords[,i]), ylab = colnames(TrackRecords)[i])
}

for (i in 1:7){
  hist((TrackRecords[,i]), xlab = paste0("Time Taken For ",colnames(TrackRecords)[i]), breaks = 20, main = paste0("Histogram of ", colnames(TrackRecords)[i]))
}

pairs(TrackRecords)

#Also check for correlation
boxplot(TrackRecords)
```

##PCA
```{r}
PCA.Track <- princomp(TrackRecords, cor = T, scores = T)
PCA.Track

PCA.newTrack <- princomp(NewTrackrecord, cor = T, scores = T)
PCA.newTrack
```


```{r}
PCA.Track$loadings
```

```{r}
head(PCA.Track$scores)
```

```{r}
biplot(PCA.Track,scale=0)
biplot(PCA.newTrack)
```

```{r}
Variance<-(PCA.Track$sdev)^2
max_Var<-round(max(Variance),1)
Components<-1:7
Components<-as.integer(Components)
plot(Components,Variance,main="Scree Plot",xlab="Number of Components",ylab="Variance",type="o",col="blue",ylim=c(0,max_Var),axes=FALSE)
axis(1,at=1:7)
axis(2,at=0:6)

```
